spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema:javafxsample
  datasource:
    url: jdbc:h2:file:~/h2/javafxsampledb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;
    username: penguin
    password: penguin123
  h2:
    console:
      enabled: true

javafx:
  title: JavaFX Spring Example